spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${HOME_URL}
    username: ${HOME_USERNAME}
    password: ${HOME_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # 여기로 옮겨야 합니다.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        generate_statistics: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE